{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "aabb68cc-303a-4d24-87cf-556f1110fb28",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "import subprocess\n",
    "import webbrowser\n",
    "import time\n",
    "\n",
    "# 1. Write the app code to a file\n",
    "app_code = \"\"\"\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from skopt.learning import GaussianProcessRegressor\n",
    "from skopt.learning.gaussian_process.kernels import Matern\n",
    "from scipy.stats import norm\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "\n",
    "st.set_page_config(page_title=\"Forensic Optimizer Pro\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📊 Forensic Bayesian Optimizer (with Step Intervals)\")\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# --- INITIALIZE STATE ---\n",
    "if 'vars_config' not in st.session_state:\n",
    "    st.session_state.vars_config = {} \n",
    "if 'experiments' not in st.session_state:\n",
    "    st.session_state.experiments = pd.DataFrame()\n",
    "\n",
    "# --- SIDEBAR: PARAMETER MANAGER ---\n",
    "with st.sidebar:\n",
    "    st.header(\"🛠️ Parameter Manager\")\n",
    "    p_name = st.text_input(\"Parameter Name\", placeholder=\"e.g. Sonication Time\")\n",
    "    p_type = st.selectbox(\"Type\", [\"Numerical\", \"Categorical\"])\n",
    "    \n",
    "    with st.form(\"var_form\", clear_on_submit=True):\n",
    "        if p_type == \"Numerical\":\n",
    "            p_unit = st.text_input(\"Unit\", placeholder=\"min\")\n",
    "            p_min = st.number_input(\"Min Range\", value=0.0)\n",
    "            p_max = st.number_input(\"Max Range\", value=100.0)\n",
    "            p_step = st.number_input(\"Step/Interval (e.g. 1.0)\", value=1.0, min_value=0.0001)\n",
    "            \n",
    "            if st.form_submit_button(\"Add Numerical Parameter\"):\n",
    "                st.session_state.vars_config[p_name] = {\n",
    "                    'type': 'Numerical', 'min': p_min, 'max': p_max, 'unit': p_unit, 'step': p_step\n",
    "                }\n",
    "                st.rerun()\n",
    "        else:\n",
    "            p_options = st.text_input(\"Options (comma separated)\", placeholder=\"MeOH, ACN\")\n",
    "            if st.form_submit_button(\"Add Categorical Parameter\"):\n",
    "                opts = [x.strip() for x in p_options.split(\",\") if x.strip()]\n",
    "                st.session_state.vars_config[p_name] = {'type': 'Categorical', 'options': opts, 'unit': ''}\n",
    "                st.rerun()\n",
    "\n",
    "    st.write(\"---\")\n",
    "    if st.button(\"🗑️ Reset All Data\"):\n",
    "        st.session_state.vars_config = {}\n",
    "        st.session_state.experiments = pd.DataFrame()\n",
    "        st.rerun()\n",
    "\n",
    "# --- DATA ENTRY ---\n",
    "if not st.session_state.vars_config:\n",
    "    st.info(\"👈 Add parameters in the sidebar. Set a 'Step' for numerical values to avoid decimal suggestions.\")\n",
    "else:\n",
    "    c1, c2 = st.columns([1, 2])\n",
    "    with c1:\n",
    "        st.subheader(\"📥 Log Result\")\n",
    "        with st.form(\"input_data\"):\n",
    "            entry = {}\n",
    "            for name, cfg in st.session_state.vars_config.items():\n",
    "                label = f\"{name} ({cfg['unit']})\" if cfg['type'] == \"Numerical\" else name\n",
    "                if cfg['type'] == \"Numerical\":\n",
    "                    entry[name] = st.number_input(label, step=cfg['step'], value=float(cfg['min']))\n",
    "                else:\n",
    "                    entry[name] = st.selectbox(label, options=cfg['options'])\n",
    "            entry['Target'] = st.number_input(\"Outcome (PAR/Recovery)\", format=\"%.6f\")\n",
    "            if st.form_submit_button(\"Log Run\"):\n",
    "                st.session_state.experiments = pd.concat([st.session_state.experiments, pd.DataFrame([entry])], ignore_index=True)\n",
    "                st.rerun()\n",
    "    with c2:\n",
    "        st.subheader(\"📝 Data Log\")\n",
    "        st.dataframe(st.session_state.experiments, use_container_width=True)\n",
    "\n",
    "# --- STATS DASHBOARD ---\n",
    "if len(st.session_state.experiments) >= 3:\n",
    "    st.divider()\n",
    "    \n",
    "    # Selection Checklist\n",
    "    plots = st.multiselect(\"Visualizations:\", [\"Convergence Plot\", \"Response Surface (3D)\", \"Parameter Importance\"], default=[\"Convergence Plot\"])\n",
    "\n",
    "    # Math Prep\n",
    "    df_enc = st.session_state.experiments.copy()\n",
    "    features = [c for c in df_enc.columns if c != 'Target']\n",
    "    for col in features:\n",
    "        if st.session_state.vars_config[col]['type'] == 'Categorical':\n",
    "            opts = st.session_state.vars_config[col]['options']\n",
    "            df_enc[col] = df_enc[col].apply(lambda x: opts.index(x))\n",
    "    \n",
    "    X, y = df_enc[features].values, df_enc['Target'].values\n",
    "    gp = GaussianProcessRegressor(kernel=Matern(nu=2.5), alpha=1e-6, normalize_y=True)\n",
    "    gp.fit(X, y)\n",
    "\n",
    "    # Plotting logic\n",
    "    if \"Convergence Plot\" in plots:\n",
    "        st.plotly_chart(px.line(y=np.maximum.accumulate(y), title=\"Best Result Found So Far\"), use_container_width=True)\n",
    "\n",
    "    if \"Response Surface (3D)\" in plots and len(features) >= 2:\n",
    "        cfg1, cfg2 = st.session_state.vars_config[features[0]], st.session_state.vars_config[features[1]]\n",
    "        x_range = np.arange(cfg1.get('min', 0), cfg1.get('max', 1)+cfg1.get('step', 1), cfg1.get('step', 1))\n",
    "        y_range = np.arange(cfg2.get('min', 0), cfg2.get('max', 1)+cfg2.get('step', 1), cfg2.get('step', 1))\n",
    "        xx, yy = np.meshgrid(x_range, y_range)\n",
    "        grid = np.c_[xx.ravel(), yy.ravel()]\n",
    "        # Hold others\n",
    "        for i in range(2, len(features)):\n",
    "            grid = np.c_[grid, np.full(xx.ravel().shape, X[np.argmax(y), i])]\n",
    "        mu = gp.predict(grid)\n",
    "        st.plotly_chart(go.Figure(data=[go.Surface(z=mu.reshape(xx.shape), x=x_range, y=y_range)]), use_container_width=True)\n",
    "\n",
    "    # --- NEXT EXPERIMENT PREDICTION (With Steps) ---\n",
    "    st.subheader(\"🔮 Practical Next Experiment\")\n",
    "    \n",
    "    # Generate random points but SNAP them to the steps\n",
    "    pts = []\n",
    "    for _ in range(5000):\n",
    "        pt = []\n",
    "        for f in features:\n",
    "            cfg = st.session_state.vars_config[f]\n",
    "            if cfg['type'] == 'Numerical':\n",
    "                val = np.random.uniform(cfg['min'], cfg['max'])\n",
    "                # SNAP TO STEP\n",
    "                snapped = np.round(val / cfg['step']) * cfg['step']\n",
    "                pt.append(np.clip(snapped, cfg['min'], cfg['max']))\n",
    "            else:\n",
    "                pt.append(np.random.choice(range(len(cfg['options']))))\n",
    "        pts.append(pt)\n",
    "    \n",
    "    pts = np.unique(np.array(pts), axis=0) # Keep only unique snapped points\n",
    "    mu, std = gp.predict(pts, return_std=True)\n",
    "    cur_best = np.max(y)\n",
    "    with np.errstate(divide='ignore'):\n",
    "        imp = mu - cur_best\n",
    "        Z = imp / std\n",
    "        ei = imp * norm.cdf(Z) + std * norm.pdf(Z)\n",
    "        ei[std <= 0.0] = 0.0\n",
    "    \n",
    "    best_pt = pts[np.argmax(ei)]\n",
    "    cols = st.columns(len(features))\n",
    "    for i, f in enumerate(features):\n",
    "        cfg = st.session_state.vars_config[f]\n",
    "        val = cfg['options'][int(best_pt[i])] if cfg['type'] == 'Categorical' else f\"{best_pt[i]:.2f} {cfg['unit']}\"\n",
    "        cols[i].metric(label=f, value=val)\n",
    "\"\"\"\n",
    "\n",
    "with open(\"forensic_opt_stepped.py\", \"w\", encoding=\"utf-8\") as f:\n",
    "    f.write(app_code)\n",
    "\n",
    "process = subprocess.Popen([\"python\", \"-m\", \"streamlit\", \"run\", \"forensic_opt_stepped.py\", \"--server.headless\", \"true\"])\n",
    "time.sleep(5)\n",
    "webbrowser.open(\"http://localhost:8501\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99a3efe6-091f-433a-9ab9-f55cfdf69396",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
